## 3.1 판다스

### 3.1.1 판다스로 csv 파일 불러오기

In [4]:
import pandas as pd

In [5]:
file_url = 'https://media.githubusercontent.com/media/musthave-ML10/data_source/main/sample.csv'

In [6]:
sample = pd.read_csv(file_url)

In [7]:
sample

Var_1  Var_2
0       1      2
1       3      4
2       2      5
3       5      6
4       3      2
5       1      1
6       2      6
7       5      7
8       6      8
9       7      4
10      7      7
11      8      3
12      9      7
13      3      9
14      2      2
15      1      3
16      2      6
17      2      4
18      3      3

### 3.1.2 데이터프레임을 살펴보는 다양한 함수

In [ ]:
sample.head()

Var_1  Var_2
0      1      2
1      3      4
2      2      5
3      5      6
4      3      2

In [ ]:
sample.head(3)

Var_1  Var_2
0      1      2
1      3      4
2      2      5

In [ ]:
sample.tail()

Var_1  Var_2
14      2      2
15      1      3
16      2      6
17      2      4
18      3      3

In [ ]:
sample.tail(10)

Var_1  Var_2
9       7      4
10      7      7
11      8      3
12      9      7
13      3      9
14      2      2
15      1      3
16      2      6
17      2      4
18      3      3

In [ ]:
sample.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Var_1   19 non-null     int64
 1   Var_2   19 non-null     int64
dtypes: int64(2)
memory usage: 432.0 bytes


In [ ]:
sample.describe()

Var_1      Var_2
count  19.000000  19.000000
mean    3.789474   4.684211
std     2.529360   2.310667
min     1.000000   1.000000
25%     2.000000   3.000000
50%     3.000000   4.000000
75%     5.500000   6.500000
max     9.000000   9.000000

### 3.1.3 데이터프레임 직접 만들기

In [8]:
sample_dic = {'name': ['John','Ann','Kevin'], 'age': [23,22,21]}

In [9]:
pd.DataFrame(sample_dic)

name  age
0   John   23
1    Ann   22
2  Kevin   21

In [10]:
[[1,2],
 [3,4],
 [5,6],
 [7,8]]

[[1, 2], [3, 4], [5, 6], [7, 8]]

In [11]:
pd.DataFrame([[1,2],[3,4],[5,6],[7,8]])

0  1
0  1  2
1  3  4
2  5  6
3  7  8

In [12]:
pd.DataFrame([[1,2],[3,4],[5,6],[7,8]], columns = ['var_1','var_2'], index=['a','b','c','d'])

var_1  var_2
a      1      2
b      3      4
c      5      6
d      7      8

### 3.1.4 데이터프레임 인덱싱

In [13]:
file_url = 'https://media.githubusercontent.com/media/musthave-ML10/data_source/main/sample_df.csv'

In [20]:
sample_df = pd.read_csv(file_url)

In [21]:
sample_df

Unnamed: 0  var_1  var_2  var_3  var_4  var_5
0          a      2      2      1      4      3
1          b      4      3      3      7      1
2          c      5      4      6      3      5
3          d      1      4      5      6      7
4          e      4      5      7      8      3
5          f      5      4      8      9      4
6          g      7      5      2      0      6
7          h      8      8      1      7      8
8          i      2      3      5      2      1
9          j      9      3      7      6      5

index_col=n : n번째 열 기준으로 인덱싱

In [22]:
sample_df = pd.read_csv(file_url, index_col=0)

In [23]:
sample_df

var_1  var_2  var_3  var_4  var_5
a      2      2      1      4      3
b      4      3      3      7      1
c      5      4      6      3      5
d      1      4      5      6      7
e      4      5      7      8      3
f      5      4      8      9      4
g      7      5      2      0      6
h      8      8      1      7      8
i      2      3      5      2      1
j      9      3      7      6      5

한줄짜리 데이터는 시리즈 형태로 출력된다. 시리즈는 데이터프레임과는 다르게 위에 컬럼명이 표기되지 않는다.

In [24]:
sample_df['var_1']

a    2
b    4
c    5
d    1
e    4
f    5
g    7
h    8
i    2
j    9
Name: var_1, dtype: int64

In [26]:
sample_df[['var_1', 'var_2']]

var_1  var_2
a      2      2
b      4      3
c      5      4
d      1      4
e      4      5
f      5      4
g      7      5
h      8      8
i      2      3
j      9      3

컬럼을 인덱싱할 때 [ ]안에는 단 하나의 값만 넣을 수 있다. 따라서 리스트 []를 이용해서 [var_1, var_2]와 같이 만들면 하나의 값으로 인식되게 만들 수 있다.

In [ ]:
sample_df[['var_1', 'var_2']]

var_1  var_2
a      2      2
b      4      3
c      5      4
d      1      4
e      4      5
f      5      4
g      7      5
h      8      8
i      2      3
j      9      3

행 인덱스 이름 기준으로 인덱싱하기 : loc[] 이용

In [ ]:
sample_df.loc['a']

var_1    2
var_2    2
var_3    1
var_4    4
var_5    3
Name: a, dtype: int64

In [ ]:
sample_df.loc[['a','b','c']]

var_1  var_2  var_3  var_4  var_5
a      2      2      1      4      3
b      4      3      3      7      1
c      5      4      6      3      5

'a':'c' 자체가 하나의 값이므로 리스트를 사용할 필요 없음

In [ ]:
sample_df.loc['a':'c']

var_1  var_2  var_3  var_4  var_5
a      2      2      1      4      3
b      4      3      3      7      1
c      5      4      6      3      5

행 위치를 기준으로 인덱싱 : iloc[] 사용

In [ ]:
sample_df.iloc[[0,1,2]]

var_1  var_2  var_3  var_4  var_5
a      2      2      1      4      3
b      4      3      3      7      1
c      5      4      6      3      5

In [ ]:
sample_df.iloc[0:2]

var_1  var_2  var_3  var_4  var_5
a      2      2      1      4      3
b      4      3      3      7      1

In [ ]:
sample_df.iloc[0:3]

var_1  var_2  var_3  var_4  var_5
a      2      2      1      4      3
b      4      3      3      7      1
c      5      4      6      3      5

iloc[] 에서는 행 뿐만 아니라 컬럼까지 동시에 인덱싱할 수 있음

In [ ]:
sample_df.iloc[0:3, 2:4]

var_3  var_4
a      1      4
b      3      7
c      6      3

컬럼을 제거하려면 drop('컬럼명', axis=1) axis=1 지정해야 한다

In [ ]:
sample_df.drop('var_1', axis=1)

var_2  var_3  var_4  var_5
a      2      1      4      3
b      3      3      7      1
c      4      6      3      5
d      4      5      6      7
e      5      7      8      3
f      4      8      9      4
g      5      2      0      6
h      8      1      7      8
i      3      5      2      1
j      3      7      6      5

In [ ]:
sample_df.drop(['var_1','var_2'], axis=1)

var_3  var_4  var_5
a      1      4      3
b      3      7      1
c      6      3      5
d      5      6      7
e      7      8      3
f      8      9      4
g      2      0      6
h      1      7      8
i      5      2      1
j      7      6      5

In [ ]:
sample_df.drop(['a','b','c'])

var_1  var_2  var_3  var_4  var_5
d      1      4      5      6      7
e      4      5      7      8      3
f      5      4      8      9      4
g      7      5      2      0      6
h      8      8      1      7      8
i      2      3      5      2      1
j      9      3      7      6      5

### 3.1.5 데이터프레임의 인덱스 변경

reset_index() 와 set_index()

In [ ]:
sample_df.reset_index()

index  var_1  var_2  var_3  var_4  var_5
0     a      2      2      1      4      3
1     b      4      3      3      7      1
2     c      5      4      6      3      5
3     d      1      4      5      6      7
4     e      4      5      7      8      3
5     f      5      4      8      9      4
6     g      7      5      2      0      6
7     h      8      8      1      7      8
8     i      2      3      5      2      1
9     j      9      3      7      6      5

In [ ]:
sample_df.reset_index(drop=True)

var_1  var_2  var_3  var_4  var_5
0      2      2      1      4      3
1      4      3      3      7      1
2      5      4      6      3      5
3      1      4      5      6      7
4      4      5      7      8      3
5      5      4      8      9      4
6      7      5      2      0      6
7      8      8      1      7      8
8      2      3      5      2      1
9      9      3      7      6      5

In [ ]:
sample_df.set_index('var_1')

var_2  var_3  var_4  var_5
var_1                            
2          2      1      4      3
4          3      3      7      1
5          4      6      3      5
1          4      5      6      7
4          5      7      8      3
5          4      8      9      4
7          5      2      0      6
8          8      1      7      8
2          3      5      2      1
9          3      7      6      5

### 3.1.6 데이터프레임의 변수별 계산

In [ ]:
sample_df.sum()

var_1    47
var_2    41
var_3    45
var_4    52
var_5    43
dtype: int64

In [ ]:
sample_df.aggregate(['sum','mean']) # agg: 여러가지 계산을 한 번에 하기

var_1  var_2  var_3  var_4  var_5
sum    47.0   41.0   45.0   52.0   43.0
mean    4.7    4.1    4.5    5.2    4.3

### 3.1.7 그룹별 계산

In [ ]:
file_url = 'https://media.githubusercontent.com/media/musthave-ML10/data_source/main/iris.csv'
iris = pd.read_csv(file_url)

In [ ]:
iris.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                6.1               3.0                4.6               1.4   
1                7.2               3.0                5.8               1.6   
2                6.7               3.1                4.4               1.4   
3                6.2               2.9                4.3               1.3   
4                4.6               3.4                1.4               0.3   

        class  
0  versicolor  
1   virginica  
2  versicolor  
3  versicolor  
4      setosa

In [ ]:
iris.groupby('class').mean()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
class                                                                
setosa                  5.006             3.428              1.462   
versicolor              5.936             2.770              4.260   
virginica               6.588             2.974              5.552   

            petal width (cm)  
class                         
setosa                 0.246  
versicolor             1.326  
virginica              2.026

In [ ]:
iris.groupby('class').agg(['count','mean']) # agg: 여러가지 계산을 한번에 하기

sepal length (cm)        sepal width (cm)        petal length (cm)  \
                       count   mean            count   mean             count   
class                                                                           
setosa                    50  5.006               50  3.428                50   
versicolor                50  5.936               50  2.770                50   
virginica                 50  6.588               50  2.974                50   

                  petal width (cm)         
             mean            count   mean  
class                                      
setosa      1.462               50  0.246  
versicolor  4.260               50  1.326  
virginica   5.552               50  2.026

### 3.1.8 변수 내 고윳값 확인하기 : unique(), nunique(), value_counts()

In [ ]:
iris['class'].unique()

array(['versicolor', 'virginica', 'setosa'], dtype=object)

In [ ]:
iris['class'].nunique() # 몇 가지 종류인지 숫자로 확인하기: nunique()

3

In [ ]:
iris['class'].value_counts() # 각 종류별로 몇 건의 데이터가 있는지 확인하기

versicolor    50
virginica     50
setosa        50
Name: class, dtype: int64

### 3.1.9 데이터프레임 합치기

In [27]:
left_url = 'https://media.githubusercontent.com/media/musthave-ML10/data_source/main/left.csv'
right_url = 'https://media.githubusercontent.com/media/musthave-ML10/data_source/main/right.csv'

left = pd.read_csv(left_url)
right = pd.read_csv(right_url)

In [ ]:
left

key  var_1  var_2
0   a      1      1
1   b      3      2
2   c      4      4
3   d      2      3
4   e      1      0

In [ ]:
right

key  var_3  var_4
0   b      4      3
1   c      6      5
2   e      3      8
3   f      2      7
4   g      3      4

merge() : 기본적으로 내부조인, 자동으로 공통 컬럼명 찾아 키값으로 활용

특정 변수를 지정해 키값으로 활용하고 싶으면 on 매개변수

In [ ]:
left.merge(right)

key  var_1  var_2  var_3  var_4
0   b      3      2      4      3
1   c      4      4      6      5
2   e      1      0      3      8

In [ ]:
left.merge(right, how = 'outer')

key  var_1  var_2  var_3  var_4
0   a    1.0    1.0    NaN    NaN
1   b    3.0    2.0    4.0    3.0
2   c    4.0    4.0    6.0    5.0
3   d    2.0    3.0    NaN    NaN
4   e    1.0    0.0    3.0    8.0
5   f    NaN    NaN    2.0    7.0
6   g    NaN    NaN    3.0    4.0

In [ ]:
left.merge(right, how = 'left')

key  var_1  var_2  var_3  var_4
0   a      1      1    NaN    NaN
1   b      3      2    4.0    3.0
2   c      4      4    6.0    5.0
3   d      2      3    NaN    NaN
4   e      1      0    3.0    8.0

join() : 기본적으로 왼쪽조인

인덱스를 기준으로 합치기 때문에, 컬럼명이 겹치면 합칠 수 없음. 특정 컬럼을 기준으로 join 하려면 컬럼을 인덱스로 설정해주어야 함 (set_index)

In [28]:
left.join(right)

ValueError: columns overlap but no suffix specified: Index(['key'], dtype='object')

In [29]:
left.drop('key', axis=1).join(right.drop('key', axis=1))

var_1  var_2  var_3  var_4
0      1      1      4      3
1      3      2      6      5
2      4      4      3      8
3      2      3      2      7
4      1      0      3      4

In [30]:
left = left.set_index('key')
right = right.set_index('key')

In [31]:
left

var_1  var_2
key              
a        1      1
b        3      2
c        4      4
d        2      3
e        1      0

In [32]:
left.join(right)

var_1  var_2  var_3  var_4
key                            
a        1      1    NaN    NaN
b        3      2    4.0    3.0
c        4      4    6.0    5.0
d        2      3    NaN    NaN
e        1      0    3.0    8.0

In [33]:
left.join(right, how='inner')

var_1  var_2  var_3  var_4
key                            
b        3      2      4      3
c        4      4      6      5
e        1      0      3      8

In [ ]:
pd.concat([left,right])

var_1  var_2  var_3  var_4
key                            
a      1.0    1.0    NaN    NaN
b      3.0    2.0    NaN    NaN
c      4.0    4.0    NaN    NaN
d      2.0    3.0    NaN    NaN
e      1.0    0.0    NaN    NaN
b      NaN    NaN    4.0    3.0
c      NaN    NaN    6.0    5.0
e      NaN    NaN    3.0    8.0
f      NaN    NaN    2.0    7.0
g      NaN    NaN    3.0    4.0

In [ ]:
pd.concat([left,right], axis=1)

var_1  var_2  var_3  var_4
key                            
a      1.0    1.0    NaN    NaN
b      3.0    2.0    4.0    3.0
c      4.0    4.0    6.0    5.0
d      2.0    3.0    NaN    NaN
e      1.0    0.0    3.0    8.0
f      NaN    NaN    2.0    7.0
g      NaN    NaN    3.0    4.0

## 3.2 넘파이

In [ ]:
import numpy as np

In [ ]:
np.array([1,2,3])

array([1, 2, 3])

In [ ]:
np.array([[1,2,3],
          [4,5,6],
          [7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.array([[[1,2,3],
           [4,5,6],
           [7,8,9]],
          [[1,2,3],
           [4,5,6],
           [7,8,9]],
          [[1,2,3],
           [4,5,6],
           [7,8,9]]])

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

### 3.2.1 배열 생성

In [ ]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [ ]:
np.array(sample_df)

array([[2, 2, 1, 4, 3],
       [4, 3, 3, 7, 1],
       [5, 4, 6, 3, 5],
       [1, 4, 5, 6, 7],
       [4, 5, 7, 8, 3],
       [5, 4, 8, 9, 4],
       [7, 5, 2, 0, 6],
       [8, 8, 1, 7, 8],
       [2, 3, 5, 2, 1],
       [9, 3, 7, 6, 5]])

In [ ]:
sample_np = np.array(sample_df)
pd.DataFrame(sample_np)

0  1  2  3  4
0  2  2  1  4  3
1  4  3  3  7  1
2  5  4  6  3  5
3  1  4  5  6  7
4  4  5  7  8  3
5  5  4  8  9  4
6  7  5  2  0  6
7  8  8  1  7  8
8  2  3  5  2  1
9  9  3  7  6  5

In [ ]:
sample_df.columns

Index(['var_1', 'var_2', 'var_3', 'var_4', 'var_5'], dtype='object')

In [ ]:
pd.DataFrame(sample_np, columns = sample_df.columns)

var_1  var_2  var_3  var_4  var_5
0      2      2      1      4      3
1      4      3      3      7      1
2      5      4      6      3      5
3      1      4      5      6      7
4      4      5      7      8      3
5      5      4      8      9      4
6      7      5      2      0      6
7      8      8      1      7      8
8      2      3      5      2      1
9      9      3      7      6      5

### 3.2.2 배열 탐색(인덱싱)

In [ ]:
sample_np

array([[2, 2, 1, 4, 3],
       [4, 3, 3, 7, 1],
       [5, 4, 6, 3, 5],
       [1, 4, 5, 6, 7],
       [4, 5, 7, 8, 3],
       [5, 4, 8, 9, 4],
       [7, 5, 2, 0, 6],
       [8, 8, 1, 7, 8],
       [2, 3, 5, 2, 1],
       [9, 3, 7, 6, 5]])

In [ ]:
sample_np[0]

array([2, 2, 1, 4, 3])

In [ ]:
sample_np[0,2]

1

In [ ]:
sample_np[0:3,2:4]

array([[1, 4],
       [3, 7],
       [6, 3]])

In [ ]:
sample_np[:,2]

array([1, 3, 6, 5, 7, 8, 2, 1, 5, 7])

### 3.2.3 배열의 연산

In [ ]:
np_a = np.array([[1,3], [0,-2]])

In [ ]:
np_a

array([[ 1,  3],
       [ 0, -2]])

In [ ]:
np_a + 10

array([[11, 13],
       [10,  8]])

In [ ]:
np_a - 5

array([[-4, -2],
       [-5, -7]])

In [ ]:
np_a * 2

array([[ 2,  6],
       [ 0, -4]])

In [ ]:
np_a+10 / 3

array([[4.33333333, 6.33333333],
       [3.33333333, 1.33333333]])

In [ ]:
np_b = np.array([[1,0], [0,1]])
np_b

array([[1, 0],
       [0, 1]])

In [ ]:
np_a + np_b

array([[ 2,  3],
       [ 0, -1]])

In [ ]:
np_a - np_b

array([[ 0,  3],
       [ 0, -3]])

In [ ]:
np_a * np_b

array([[ 1,  0],
       [ 0, -2]])

In [ ]:
np_a @ np_b

array([[ 1,  3],
       [ 0, -2]])

### 3.2.4 임의의 숫자를 뽑는 random.XXX() 함수

In [ ]:
np.random.randint(11)

10

In [ ]:
np.random.randint(50, 71)

51

In [ ]:
np.random.randint(50, 71, 5)

array([68, 67, 52, 65, 63])

In [ ]:
np.random.choice(['red', 'green','white','black','blue'],size=3)

array(['white', 'black', 'blue'], dtype='<U5')

In [ ]:
np.random.choice(['red', 'green','white','black','blue'],size=3, replace=False)

array(['blue', 'red', 'green'], dtype='<U5')

### 3.2.5 그외 유용한 함수

In [ ]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [ ]:
np.linspace(1,10,4)

array([ 1.,  4.,  7., 10.])